version: '3'
services:
    pg_database:
        image: 'postgres:13'
        user: 'postgres'
        volumes:
            - postgres-data:/var/lib/postgresql/data
            - ./bin/pg-docker-entrypoint-initdb.sql:/docker-entrypoint-initdb.d/schema.sql
        command:
            - 'postgres'
            - '-c'
            - 'listen_addresses=*'
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=task-manager

volumes:
    postgres-data:
